spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/ecomm_orders
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8081
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
  packages-to-scan: com.ecommerce.product.controller